- name: SYSTEM NGINX nginx must be installed
  apt:
    name:
      - nginx-light
    state: present

  notify: NGINX Restart Nginx Service

- name: SYSTEM NGINX Remove default server on sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: NGINX Restart Nginx Service