- name: SYSTEM NGINX nginx must be installed
  apt: pkg={{ item }} state=present
  with_items:
  - nginx-light
  notify: NGINX Restart Nginx Service

- name: SYSTEM NGINX Remove default server on sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: NGINX Restart Nginx Service